# Generated by Django 5.1.4 on 2024-12-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comments',
        ),
    ]
